name: deploy to github pages

on:
  repository_dispatch:
    types:
      - my-talks
      - my-resume
  push:
    paths-ignore:
      - '**/README.md'
      - LICENSE
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/README.md'
      - LICENSE
    branches:
      - master
  #schedule:
    #scheduled deployments for future posts during weekdays
   # - cron: "22 22 * * 1-5"
  workflow_dispatch:

env:
  CNAME: "callebaut.io"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with: 
          hugo-version: '0.89.2'
      
      - name: Build
        run: hugo --minify

        # only publish an artifact when pushing to main. 
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        if: contains(github.ref, 'main') && (github.event_name == 'push' || github.event_name == 'schedule')
        with:
          name: personal-website
          path: public/

  #only deploy to gh-pages when pushing to main
  deploy:
    runs-on: Ubuntu-20.04
    needs: build
    if: contains(github.ref, 'main') && (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: personal-website
          path: ./public
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: ${{ github.event.head_commit.message }}
          cname: ${{ env.CNAME }}
      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Get current date
        id: today
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.today.outputs.date }}-${{ steps.slug.outputs.sha8 }}
          release_name: Release v${{ steps.today.outputs.date }}-${{ steps.slug.outputs.sha8 }}
          draft: false
          prerelease: false

